#!/bin/sh
# needs to run as root of a UTS namespace to set hostname
# uses fake "systemctl"/"sendmail" programs to validate the output
M_O_F="$PWD/out/build/bin/mail_on_failure"
cd test/m_o_f || exit
hostname tarta

PATH=".:$PATH"
err=0
for f in *.service; do
	"$M_O_F" --verbose "$f" 2>&1 | diff -u "${f%.service}.output" - || err=1
done
exit $err
