#!/bin/sh
#
# this hook will check for TABs in python sources before commit
#
# installation steps:
# 1) git config --local --add core.whitespace tab-in-indent
# 2) put his file in .git/hooks , chmod +x

# Redirect output to stderr.
exec 1>&2

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached HEAD -- src/bin/*
