#!/bin/sh

# this is a trivial fake sendmail for development of "mail_for_job" tool

# export SENDMAIL=$PWD/contrib/sendmail-cat
# out/build/bin/mail_for_job cron-monthly-check-dfsg-status.service

exec cat
